### ISSUE TITLE
AbstractProlEditor  characters can get lost when the system is imported to Eclipse

### ISSUE THREAD

**Issue by KnowledgeGarden** [raydac/jprol#1]
The solution for characters like â seems to be to hand copy them back (if, in fact, they are messed up) from source, then save the file as UTF8.

**Comment by KnowledgeGarden** [comment]
Personally, I think this issue could easily be closed; it's not really a bug to fix; rather, it's a file handling issue related to what Windows can do to UTF-8 files if you don't pay attention. After importing the code to Eclipse, just hand copy the clean code back to that file.When you save, Eclipse will ask if you want to save as UTF-8. Overall, the system came right up and is being easy to explore.

**Comment by raydac** [comment]
I have improved reading-saving operations to use UTF-8 for them, now if you save or write files from the embeddded GUI editor then they will be saved in UTF-8
https://github.com/raydac/jprol/commit/019244aa415f97c1eb8d53cdc245d7e4fc034983
