### ISSUE TITLE
Are Prolog modules supported?

### ISSUE THREAD

**Issue by vasily-kartashov** [raydac/jprol#3]
As in:

```
module/2
use_module/1
library/1 
```

**Comment by raydac** [comment]
jprol doesn't support prolog modules, it has very restricted set of embedded predicates

**Comment by vasily-kartashov** [comment]
It's fairly straightforward to add predicates to your implementation, so I am not really bothered. 

Can you give me a couple of pointers please on where to look at if I wished to add `:- module/2` and `:- use_module/1` to your implementation?
